<?php
    session_start();
$_SESSION['field1'] = $_SESSION['field1'];
$_SESSION['field2'] = $_SESSION['field2'];
$_SESSION['field3'] = $_SESSION['field3']; 
$_SESSION['field4'] = $_SESSION['field4'];
$_SESSION['field5'] = $_SESSION['field5'];
$_SESSION['field6'] = $_SESSION['field6']; 
$_SESSION['field7'] = $_SESSION['field7']; 
$_SESSION['field8'] = $_SESSION['field8'];
$_SESSION['field9'] = $_SESSION['field9'];
$_SESSION['field10'] = $_SESSION['field10']; 
$_SESSION['field11'] = $_SESSION['field11']; 
$_SESSION['field12'] = $_SESSION['field12'];
$_SESSION['field13'] = $_SESSION['field13'];
$_SESSION['field14'] = $_SESSION['field14']; 
$_SESSION['field15'] = $_SESSION['field15']; 
$_SESSION['field16'] = $_SESSION['field16'];
$_SESSION['field17'] = $_SESSION['field17'];
$_SESSION['field18'] = $_SESSION['field18']; 
$_SESSION['field19'] = $_SESSION['field19']; 
$_SESSION['field20'] = $_SESSION['field20'];
$_SESSION['field21'] = $_SESSION['field21'];
$_SESSION['field22'] = $_SESSION['field22']; 
$_SESSION['field23'] = $_SESSION['field23']; 
$_SESSION['field24'] = $_SESSION['field24'];
$_SESSION['field25'] = $_SESSION['field25'];
$_SESSION['field26'] = $_SESSION['field26']; 
$_SESSION['field27'] = $_SESSION['field27']; 
$_SESSION['field28'] = $_SESSION['field28'];
$_SESSION['field29'] = $_SESSION['field29'];
$_SESSION['field30'] = $_SESSION['field30']; 
$_SESSION['field31'] = $_SESSION['field31'];
$_SESSION['field32'] = $_SESSION['field32'];
$_SESSION['field33'] = $_SESSION['field33']; 
$_SESSION['field34'] = $_SESSION['field34']; 
$_SESSION['field35'] = $_SESSION['field35'];
$_SESSION['field36'] = $_SESSION['field36'];
$_SESSION['field37'] = $_SESSION['field37']; 
$_SESSION['field38'] = $_SESSION['field38']; 
$_SESSION['field39'] = $_SESSION['field39'];
$_SESSION['field40'] = $_SESSION['field40'];
$_SESSION['field41'] = $_SESSION['field41']; 
$_SESSION['field42'] = $_SESSION['field42']; 
$_SESSION['field43'] = $_SESSION['field43'];
$_SESSION['field44'] = $_SESSION['field44'];
$_SESSION['field45'] = $_SESSION['field45']; 
$_SESSION['field46'] = $_SESSION['field46'];
$_SESSION['field47'] = $_SESSION['field47'];
$_SESSION['field48'] = $_SESSION['field48']; 
$_SESSION['field49'] = $_SESSION['field49']; 
$_SESSION['field50'] = $_POST['field50'];
$_SESSION['field51'] = $_POST['field51'];
$_SESSION['field52'] = $_POST['field52'];
$_SESSION['field53'] = $_POST['field53']; 
$_SESSION['field54'] = $_POST['field54'];
$_SESSION['field55'] = $_POST['field55'];
$_SESSION['field56'] = $_POST['field56'];
$_SESSION['field57'] = $_POST['field57']; 
$_SESSION['field58'] = $_POST['field58'];
$_SESSION['field59'] = $_POST['field59']; 
$_SESSION['field60'] = $_POST['field60'];
$_SESSION['field61'] = $_POST['field61'];
$_SESSION['field62'] = $_POST['field62'];
$_SESSION['field63'] = $_POST['field63']; 
$_SESSION['field64'] = $_POST['field64'];
$_SESSION['field66'] = $_POST['field66'];
$_SESSION['field66'] = $_POST['field66'];
$_SESSION['field67'] = $_POST['field67']; 
$_SESSION['field68'] = $_POST['field68'];
$_SESSION['field69'] = $_POST['field69']; 
$_SESSION['field70'] = $_POST['field70'];
$_SESSION['field70'] = $_POST['field70'];
$_SESSION['field71'] = $_POST['field71'];
$_SESSION['field72'] = $_POST['field72'];
$_SESSION['field73'] = $_POST['field73']; 
$_SESSION['field74'] = $_POST['field74'];
$_SESSION['field75'] = $_POST['field75'];
$_SESSION['field76'] = $_POST['field76'];
$_SESSION['field77'] = $_POST['field77']; 
$_SESSION['field78'] = $_POST['field78'];
$_SESSION['field79'] = $_POST['field79']; 
$_SESSION['field80'] = $_POST['field80'];
$_SESSION['field81'] = $_POST['field81'];
$_SESSION['field82'] = $_POST['field82'];
$_SESSION['field83'] = $_POST['field83']; 
$_SESSION['field84'] = $_POST['field84'];
$_SESSION['field85'] = $_POST['field85'];
$_SESSION['field86'] = $_POST['field86'];
$_SESSION['field87'] = $_POST['field87']; 
$_SESSION['field88'] = $_POST['field88'];
$_SESSION['field89'] = $_POST['field89']; 
$_SESSION['field90'] = $_POST['field90'];
$_SESSION['field91'] = $_POST['field91'];
$_SESSION['field92'] = $_POST['field92'];
$_SESSION['field93'] = $_POST['field93']; 
$_SESSION['field94'] = $_POST['field94'];
$_SESSION['field95'] = $_POST['field95'];
$_SESSION['field96'] = $_POST['field96']; 
$_SESSION['field97'] = $_POST['field97'];
$_SESSION['field98'] = $_POST['field98'];
$_SESSION['field99'] = $_POST['field99'];
$_SESSION['field100'] = $_POST['field100'];
$_SESSION['field101'] = $_POST['field101'];
$_SESSION['field102'] = $_POST['field102']; 
$_SESSION['field103'] = $_POST['field103'];
$_SESSION['field104'] = $_POST['field104'];
$_SESSION['field105'] = $_POST['field105']; 

/* Set e-mail recipient */
$youremail  = $_SESSION[field12]; // this is the email address collected from the form 
$subject = "Application Received";
$headers = "From: info@northp.com";
$headers .= "MIME-Version: 1.0\r\n";
$headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";

/* Let's prepare the message for the e-mail */
// use wordwrap() if lines are longer than 70 characters
 $message = wordwrap($message,70, "\r\n");
 $message = '<html><body>';
 $message .= '<a href="http://northp.com/"><img src="http://northp.cohoservwebsites.com/wp-content/uploads/sites/6/2014/01/logo.png" alt="North Pacific Management"></a>';
 $message .= '<table style="border-color: #666;" cellpadding="10">';
 $message .= "<tr><td>Dear " . strip_tags($_SESSION['field5']) . ",</td></tr>";
 $message .= "<tr><td>Thank you for your interest in the " . strip_tags($_SESSION['field2']) . " position at " . strip_tags($_SESSION['field1']) . "  . We will contact you.</td></tr>";
 $message .= "</table>";
 $message .= "</body></html>";

/* Send the message using mail() function */
mail($youremail, $subject, $message, $headers);	
	
/* Set e-mail recipient */
$myemail  = ("leslie.yosef@northp.com, yosefleslie@rocketmail.com");
$subject = "Submitted Application";

$headers = "From: " . strip_tags($_SESSION['email']) . "\r\n";
$headers .= "MIME-Version: 1.0\r\n";
$headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";

/* Let's prepare the message for the e-mail */
$message = '<html><body>';
$message .= '<h1>Job Application</h1>';
$message .= '<table style="border-color: #666;">';
$message .= "<tr><td><strong>Location applying to:</strong> </td><td>" . strip_tags($_SESSION['field1']) . "</td></tr>";
$message .= "<tr><td><strong>Position:</strong> </td><td>" . strip_tags($_SESSION['field2']) . "</td></tr>";
$message .= "<tr><td><strong>How you learned about us:</strong> </td><td>" . strip_tags($_SESSION['field3']) . " " . strip_tags($_SESSION['field4']) . "</td></tr>";
$message .= "<tr><td><strong>Full Name:</strong> </td><td>" . strip_tags($_SESSION['field5']) . " " . strip_tags($_SESSION['field7']) . " " . strip_tags($_SESSION['field6']) . "</td></tr>";
$message .= "<tr><td><strong>Address:</strong> </td><td>" . strip_tags($_SESSION['field8']) . ", " . strip_tags($_SESSION['field9']) . " " . strip_tags($_SESSION['field10']) . " " . strip_tags($_SESSION['field11']) . "</td></tr>";
$message .= "<tr><td><strong>Email:</strong> </td><td>" . strip_tags($_SESSION['field12']) . "</td></tr>";
$message .= "<tr><td><strong>Phone:</strong> </td><td>" . strip_tags($_SESSION['field13']) . "</td></tr>";
$message .= "<tr><td><strong>Alternate Phone:</strong> </td><td>" . strip_tags($_SESSION['field14']) . "</td></tr>";
$message .= "<tr><td><strong>Best time for contact:</strong> </td><td>" . strip_tags($_SESSION['field15']) . "</td></tr>";
$message .= "<tr><td><strong>Under 18: proof of eligibility:</strong> </td><td>" . strip_tags($_SESSION['field16']) . "</td></tr>";
$message .= "<tr><td><strong>Applied with us before:</strong> </td><td>" . strip_tags($_SESSION['field17']) . "</td></tr>";
$message .= "<tr><td><strong>Date of last application:</strong> </td><td>" . strip_tags($_SESSION['field18']) . "</td></tr>";
$message .= "<tr><td><strong>Employed with us before:</strong> </td><td>" . strip_tags($_SESSION['field19']) . "</td></tr>";
$message .= "<tr><td><strong>Dates of employment:</strong> </td><td>" . strip_tags($_SESSION['field20']) . " - " . strip_tags($_SESSION['field21']) . "</td></tr>";
$message .= "<tr><td><strong>Currently employed:</strong> </td><td>" . strip_tags($_SESSION['field22']) . "</td></tr>";
$message .= "<tr><td><strong>Contact your present employer:</strong> </td><td>" . strip_tags($_SESSION['field23']) . "</td></tr>";
$message .= "<tr><td><strong>Been convicted of felony/misdemeaner:</strong> </td><td>" . strip_tags($_SESSION['field24']) . "</td></tr>";
$message .= "<tr><td><strong>Available: Full Time</strong> </td><td>" . strip_tags($_SESSION['field25']) . "</td></tr>";
$message .= "<tr><td><strong>Available: Part Time</strong> </td><td>" . strip_tags($_SESSION['field25']) . " - " . strip_tags($_SESSION['field27']) . "</td></tr>";
$message .= "<tr><td><strong>Available: Temporary</strong> </td><td>" . strip_tags($_SESSION['field25']) . " - " . strip_tags($_SESSION['field29']) . strip_tags($_SESSION['field30']) . "</td></tr>";
$message .= "<tr><td><strong>On lay-off status/subject to recall:</strong> </td><td>" . strip_tags($_SESSION['field31']) . "</td></tr>";
$message .= "<tr><td><strong>Can you travel:</strong> </td><td>" . strip_tags($_SESSION['field32']) . "</td></tr>";
$message .= "<tr><td><strong>High School:</strong> </td><td>" . strip_tags($_SESSION['field33']) . "</td></tr>";
$message .= "<tr><td><strong>High School Study:</strong> </td><td>" . strip_tags($_SESSION['field34']) . "</td></tr>";
$message .= "<tr><td><strong>High School Years:</strong> </td><td>" . strip_tags($_SESSION['field35']) . "</td></tr>";
$message .= "<tr><td><strong>High School Degree:</strong> </td><td>" . strip_tags($_SESSION['field36']) . "</td></tr>";
$message .= "<tr><td><strong>Undergraduate College:</strong> </td><td>" . strip_tags($_SESSION['field37']) . "</td></tr>";
$message .= "<tr><td><strong>Undergraduate College Study:</strong> </td><td>" . strip_tags($_SESSION['field38']) . "</td></tr>";
$message .= "<tr><td><strong>Undergraduate College Years:</strong> </td><td>" . strip_tags($_SESSION['field39']) . "</td></tr>";
$message .= "<tr><td><strong>Undergraduate College Degree:</strong> </td><td>" . strip_tags($_SESSION['field40']) . "</td></tr>";
$message .= "<tr><td><strong>Graduate/Professional:</strong> </td><td>" . strip_tags($_SESSION['field41']) . "</td></tr>";
$message .= "<tr><td><strong>Graduate/Professional Study:</strong> </td><td>" . strip_tags($_SESSION['field42']) . "</td></tr>";
$message .= "<tr><td><strong>Graduate/Professional Years:</strong> </td><td>" . strip_tags($_SESSION['field43']) . "</td></tr>";
$message .= "<tr><td><strong>Graduate/Professional Degree:</strong> </td><td>" . strip_tags($_SESSION['field44']) . "</td></tr>";
$message .= "<tr><td><strong>Other:</strong> </td><td>" . strip_tags($_SESSION['field46']) . "</td></tr>";
$message .= "<tr><td><strong>Other Study:</strong></td><td>" . strip_tags($_SESSION['field47']) . "</td></tr>";
$message .= "<tr><td><strong>Other Years:</strong></td><td>" . strip_tags($_SESSION['field48']) . "</td></tr>";
$message .= "<tr><td><strong>Other Degree:</strong></td><td>" . strip_tags($_SESSION['field49']) . "</td></tr>";
$message .= "<tr><td><strong>1st Employer:</strong></td><td>" . strip_tags($_SESSION['field50']) . "</td></tr>";
$message .= "<tr><td><strong>1st Employer Address:</strong> </td><td>" . strip_tags($_SESSION['field51']) . ", " . strip_tags($_SESSION['field52']) . " " . strip_tags($_SESSION['field53']) . " " . strip_tags($_SESSION['field54']) . "</td></tr>";
$message .= "<tr><td><strong>Work Performed:</strong> </td><td>" . strip_tags($_SESSION['field60']) . "</td></tr>";
$message .= "<tr><td><strong>Dates Employed:</strong> </td><td>" . strip_tags($_SESSION['field55']) . " - " . strip_tags($_SESSION['field56']) . "</td></tr>";
$message .= "<tr><td><strong>Reason for leaving::</strong> </td><td>" . strip_tags($_SESSION['field57']) . "</td></tr>";
$message .= "<tr><td><strong>Hourly Rates:</strong> </td><td>" . "Beg: " . strip_tags($_SESSION['field58']) . "  End: " . strip_tags($_SESSION['field59']) . "</td></tr>";
$message .= "<tr><td><strong>Supervisor:</strong> </td><td>" . strip_tags($_SESSION['field61']) . "</td></tr>";
$message .= "<tr><td><strong>May we contact:</strong> </td><td>" . strip_tags($_SESSION['field62']) . " Phone: " . strip_tags($_SESSION['field63']) . "</td></tr>";
$message .= "<tr><td><strong>2nd Employer:</strong> </td><td>" . strip_tags($_SESSION['field64']) . "</td></tr>";
$message .= "<tr><td><strong>2nd Employer Address:</strong> </td><td>" . strip_tags($_SESSION['field65']) . ", " . strip_tags($_SESSION['field67']) . " " . strip_tags($_SESSION['field68']) . " " . strip_tags($_SESSION['field69']) . "</td></tr>";
$message .= "<tr><td><strong>Work Performed:</strong> </td><td>" . strip_tags($_SESSION['field66']) . "</td></tr>";
$message .= "<tr><td><strong>Dates Employed:</strong> </td><td>" . strip_tags($_SESSION['field70']) . " - " . strip_tags($_SESSION['field71']) . "</td></tr>";
$message .= "<tr><td><strong>Reason for leaving::</strong> </td><td>" . strip_tags($_SESSION['field72']) . "</td></tr>";
$message .= "<tr><td><strong>Hourly Rates:</strong> </td><td>" . "Beg: " . strip_tags($_SESSION['field73']) . "  End: " . strip_tags($_SESSION['field74']) . "</td></tr>";
$message .= "<tr><td><strong>Supervisor:</strong> </td><td>" . strip_tags($_SESSION['field75']) . "</td></tr>";
$message .= "<tr><td><strong>May we contact:</strong> </td><td>" . strip_tags($_SESSION['field76']) . " Manager: " . strip_tags($_SESSION['field77']) . "</td></tr>";
$message .= "<tr><td><strong>3rd Employer:</strong> </td><td>" . strip_tags($_SESSION['field78']) . "</td></tr>";
$message .= "<tr><td><strong>3rd Employer Address:</strong> </td><td>" . strip_tags($_SESSION['field79']) . ", " . strip_tags($_SESSION['field81']) . ", " . strip_tags($_SESSION['field82']) . " " . strip_tags($_SESSION['field83']) . "</td></tr>";
$message .= "<tr><td><strong>Work Performed:</strong> </td><td>" . strip_tags($_SESSION['field80']) . "</td></tr>";
$message .= "<tr><td><strong>Dates Employed:</strong> </td><td>" . strip_tags($_SESSION['field84']) . " to " . strip_tags($_SESSION['field85']) . "</td></tr>";
$message .= "<tr><td><strong>Reason for leaving::</strong> </td><td>" . strip_tags($_SESSION['field86']) . "</td></tr>";
$message .= "<tr><td><strong>Hourly Rates:</strong> </td><td>" . "Beg: " . strip_tags($_SESSION['field87']) . "  End: " . strip_tags($_SESSION['field88']) . "</td></tr>";
$message .= "<tr><td><strong>Supervisor:</strong> </td><td>" . strip_tags($_SESSION['field89']) . "</td></tr>";
$message .= "<tr><td><strong>May we contact:</strong> </td><td>" . strip_tags($_SESSION['field90']) . " Manager: "  . strip_tags($_SESSION['field91']) . "</td></tr>";
$message .= "<tr><td><strong>Summary of job-related skills:</strong> </td><td>" . strip_tags($_SESSION['field92']) . "</td></tr>";
$message .= "<tr><td><strong>1st Professional Reference:</strong> </td><td>" . strip_tags($_SESSION['field93']) . "</td></tr>";
$message .= "<tr><td><strong>1st Professional Reference Phone:</strong> </td><td>" . strip_tags($_SESSION['field94']) . "</td></tr>"; 
$message .= "<tr><td><strong>1st Professional Reference Best Time:</strong> </td><td>" . strip_tags($_SESSION['field95']) . "</td></tr>"; 
$message .= "<tr><td><strong>1st Professional Reference Occupation:</strong> </td><td>" . strip_tags($_SESSION['field96']) . "</td></tr>";
$message .= "<tr><td><strong>2nd Professional Reference:</strong> </td><td>" . strip_tags($_SESSION['field97']) . "</td></tr>";
$message .= "<tr><td><strong>2nd Professional Reference Phone:</strong> </td><td>" . strip_tags($_SESSION['field98']) . "</td></tr>"; 
$message .= "<tr><td><strong>2nd Professional Reference Best Time:</strong> </td><td>" . strip_tags($_SESSION['field99']) . "</td></tr>"; 
$message .= "<tr><td><strong>2nd Professional Reference Occupation:</strong> </td><td>" . strip_tags($_SESSION['field100']) . "</td></tr>";
$message .= "<tr><td><strong>3rd Professional Reference:</strong> </td><td>" . strip_tags($_SESSION['field101']) . "</td></tr>";
$message .= "<tr><td><strong>3rd Professional Reference Phone:</strong> </td><td>" . strip_tags($_SESSION['field102']) . "</td></tr>"; 
$message .= "<tr><td><strong>3rd Professional Reference Best Time:</strong> </td><td>" . strip_tags($_SESSION['field103']) . "</td></tr>"; 
$message .= "<tr><td><strong>3rd Professional Reference Occupation:</strong> </td><td>" . strip_tags($_SESSION['field104']) . "</td></tr>";
$message .= "<tr><td><strong>Accept terms of use:</strong> </td><td>" . strip_tags($_SESSION['field105']) . "</td></tr>";
$message .= "</table>";
$message .= "</body></html>";

/* Send the message using mail() function */
mail($myemail, $subject, $message, $headers);


/* Redirect visitor to the thank you page */
header('Location: http://lesliestesting.com/thanks.htm');
exit();
?>